replicaCount: 2

image:
  repository: sokrypes/pedri-app
  pullPolicy: Always
  tag: "latest"

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

serviceAccount:
  create: false
  name: ""
