replicaCount: 1

image:
  repository: sokrypes/pedri-app
  tag: "4"
  pullPolicy: Always

service:
  type: NodePort 
  port: 80
  targetPort: 80
  nodePort: 31111     

containerPort: 80

resources: {}